import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [value, setValue] = useState('');
  const [timeZone, setTimeZone] = useState('');

  const FRONTEND_URL = process.env.HOST || 'http://localhost:3000';

  const handleSubmit = async (e) => {
    e.preventDefault();

    console.log('ok');
    try {
      const req = await fetch(
        `${FRONTEND_URL}/api/african-time?timezone=${value}`
      );

      const res = await req.json();
      const { time } = await res;
      console.log(time);
      setTimeZone(time);
    } catch (error) {}
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1>Test this api</h1>

        <form onSubmit={handleSubmit}>
          <select value={value} onChange={(e) => setValue(e.target.value)}>
            <option value='' hidden>
              Select a TimeZone
            </option>
            <option value='CVT'>Cape Verde Time ( GMT-1 )</option>
            <option value='GMT'>Greenwich Mean Time ( GMT )</option>
            <option value='WAT'>West Africa Time ( GMT+1 )</option>
            <option value='CAT'>Central Africa Time ( GMT+2 )</option>
            <option value='EAT'>East Africa Time ( GMT+3 )</option>
            <option value='MT'>
              Mauritius Time & Seychelles Time ( GMT+4 )
            </option>
          </select>

          <button>Check timezone</button>
        </form>

        {timeZone && (
          <div>
            <p>TimeZone: {timeZone}</p>
          </div>
        )}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
